kind: Template
apiVersion: v1
objects: 
      - kind: BuildConfig
        apiVersion: v1
        metadata: 
          name: 3build-1
        annotations: 
          description: The deployable image 3rd category
          template.alpha.openshift.io/wait-for-ready: true
        spec: 
          source: 
            git: 
              uri: https://github.com/karthik1113bitcoin/p3.git
            images: 
              - from: 
                 kind: ImageStreamTag
                 name: release_image:latest
                 namespace: p3
                paths: 
                - destinationDir: /tmp/curr/ 
                  sourcePath: /tmp/cust/
          strategy: 
            dockerStrategy: 
              dockerfilePath: 3dockerfile
          output: 
            to: 
              kind: DockerImage
              name: 172.30.1.1:5000/p2/jk_cn_release:latest
parameters:
  - name: GENERIC_WEBHOOK_SECRET
    description: A secret string used to configure the GitHub webhook
    generate: expression 
    from: "[a-zA-Z0-9]{40}" 
  - name: REPLICA_COUNT
    description: Number of replicas to run
    value: "1"
    required: false
message: "... The GitHub webhook secret is ${GENERIC_WEBHOOK_SECRET} ..." 
